AWSTemplateFormatVersion: 2010-09-09
Description: Basic EC2 Instance.

Resources:
  DevEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0e2ff28bfb72a4e45
      InstanceType: t2.micro
      KeyName: feb19
      NetworkInterfaces: 
      - AssociatePublicIpAddress: "true"
        DeviceIndex: "0"
        GroupSet: 
          - Ref: "SSHSecurityGroup"
        SubnetId: subnet-0a0fb06d
          
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Scott Group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '1433'
          ToPort:   '1433'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '80'
          ToPort:   '80'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '389'
          ToPort:   '389'
          CidrIp: 0.0.0.0/0
      VpcId: vpc-eaaa6290
     
